### ISSUE TITLE
프론트 메인페이지 생성

### ISSUE THREAD

**Issue by 9JHP9** [nhnacademy-be5-t2m/t2m_BookStore#108]
### ⚠️ Issue
도메인 기본 템플릿 생성을 할 것 

### ✏️ ToDoList
- [ ] 메인페이지 템플릿을 만들어 볼 것
- [ ] 도메인에 연결하여 실행 시 출력되는지 확인할 것

**Comment by ssstopeun** [comment]
- [ ] 권한에 따른 header를 다르게 설정
- [ ] 페이지에 따른 header, navigator 설정
