### ISSUE TITLE
회원 등급

### ISSUE THREAD

**Issue by ssstopeun** [nhnacademy-be5-t2m/t2m_BookStore#19]
### ⚠️ Issue
주문금액에 따라 회원 등급이 부여된다.
3달 이내의 순수 주문금액에 따라 회원 등급이 나눠진다.

순수금액 : 주문금액 - (쿠폰 + 배송비 + 취소금액 + 포장비)

- 일반 : 10만원 이하           순수금액의 1프로 포인트 적립
- 로얄 : 10만원 ~ 20만원   순수금액의 2프로 포인트 적립
- 골드 : 20만원 ~ 30만원   순수금액의 3프로 포인트 적립
- 플래티넘 : 30만원 이상   순수금액의 4프로 포인트 적립

### ✏️ ToDoList
- [ ] 마이페이지에 나의 등급버튼 구현
- [ ] 등급 상세페이지
       - userId로 순수금액 데이터로 등급 설정
       - 순수금액과 등급 view

### ➡️ Flow
1.  마이페이지에서 나의등급버튼을 클릭한다.
2.  주문순수금액과 함께 나의 등급이 나온다.

**Comment by ssstopeun** [comment]
등급 처리를 어떻게 해야할지 생각해야 한다.

- 포인트적립시점 -> 주문시
- 등급처리시점 -> 주문시 3개월간 주문 금액 + 현재 주문 을 토대로 갱신
- 주문 취소/반품을 했을때 -> 등급 갱신
- 포인트 부여후 반품/취소 시 포인트 되돌림

**Comment by jinnkimm7** [comment]
#40 이전 달 3개월 기준 순수금액들을 계산해 등급일괄처리
