### ISSUE TITLE
데이터베이스 접속 정보 암호화

### ISSUE THREAD

**Issue by ssstopeun** [nhnacademy-be5-t2m/t2m_BookStore#55]
- Secure Key manager

https://www.nhncloud.com/kr/service/security/secure-key-manager

https://docs.nhncloud.com/ko/Security/Secure%20Key%20Manager/ko/overview/

**Comment by KimSu-Been** [comment]
##API 참고
https://docs.nhncloud.com/ko/Security/Secure%20Key%20Manager/ko/api-guide-v1.0/


##Console을 통해 자신의 IP등록
- nhn cloud console - security - 키 저장소 g2nee 선택 - IPv4 주소 관리 - 개발할 pc의 ip주소 입력
- 허용된 ip만 api를 사용하여 데이터베이스 접속 정보를 가져올 수 있음
