### ISSUE TITLE
OSIV (Open Session In View)

### ISSUE THREAD

**Issue by ssstopeun** [nhnacademy-be5-t2m/t2m_BookStore#56]
### ⚠️ Issue
- osiv 학습 및 정리( 팀원과 공유)

- application.properties에 
→ spring.jpa.open-in-view=false 로 설정
- OSIV를 끄면 트랜잭션을 종료할 때 영속성 컨텍스트를 닫고, 데이터베이스 커넥션도 반환
  → 커넥션 리소스를 낭비하지 않음
  - 모든 지연로딩을 트랜잭션 안에서 처리해야 함: 지연 로딩 코드를 트랜잭션 안으로 넣어야 하고, view에서 지연로딩이 동작하지 않음

- 커맨드와 쿼리를 분리
  - ~Service: 핵심 비즈니스 로직
  - ~QueryService: 화면, API에 맞춘 로직(주로 읽기 전용)

**Comment by KimSu-Been** [comment]
https://hstory0208.tistory.com/entry/SpringJPA-OSIV-%EC%A0%84%EB%9E%B5%EC%9D%B4%EB%9E%80-%EC%96%B8%EC%A0%9C-%EC%82%AC%EC%9A%A9%ED%95%B4%EC%95%BC-%ED%95%A0%EA%B9%8C

https://wildeveloperetrain.tistory.com/315
