### ISSUE TITLE
2_도서 목록 조회

### ISSUE THREAD

**Issue by ehdals0405** [nhnacademy-be5-t2m/t2m_BookStore#9]
### ⚠️ Issue
- 도서를 목록을 조회할 수 있다

### ✏️ ToDoList
- [ ] 조회수가 많은 순으로 도서를 조회하는 API 구현
- 계속 DB에 접근하는 건 효율이 좋지 않음(쿼리 증가) + 데이터베이스 locking 문제
- Redis에 임시 저장했다가 일정 시간마다 DB에 저장하는 방법(이걸 많이 사용하는듯?)
- 쿠키를 사용하는 방법
- [ ] 메인 화면 출력 시 조회 수가 많은 순서대로 8개 출력 페이지 5개씩 표현한다.
- [ ] 도서를 상세 조회하는 API 구현
-> 도서 사진을 클릭 시 도서의 상세한 정보와 리뷰를 볼 수 있다. 
- [ ] 도서를 제목, 카테고리, 작가, 출판사로 조회하는 API 구현
- [ ] 검색창에 제목으로 도서를 검색하거나 탭에서 조건을 선택하여 검색할 수 있고 12개씩 출력하며
       페이지는 5개씩 표현

### ➡️Flow
1. 메인 페이지에서 조회수 많은 도서를 확인
2. 상단 검색창에서 제목을 검색하여 도서를 검색
3. 탭에서 카테고리, 작가 등을 선택하여 조건에 맞는 도서 검색
4. 도서를 클릭하여 도서 상세 정보를 조회

**Comment by jinnkimm7** [comment]
#40 인기 도서 (전 달의 인기있는 도서 10개)
