### ISSUE TITLE
sql 쿼리 작성해 데이터베이스 확인과정

### ISSUE THREAD

**Issue by ssstopeun** [nhnacademy-be5-t2m/t2m_BookStore#92]
- sql을 작성해 데이터베이스의 join등 연관관계 처리가 잘 되었는지 확인한다.

**Comment by KimSu-Been** [comment]
> ##카테고리 쿼리: 상위 카테고리에 포함되는 카테고리 검색
> 
> ```
> SELECT c.*
> FROM Categories as c
>          JOIN CategoryPath AS p
>               ON c.categoryId = p.descendantId
> WHERE p.ancestorId = 원하는 최상위 카테고리 id
> ```
> 
> ![Image](https://private-user-images.githubusercontent.com/89886506/314348244-4de88c6f-091e-4479-bb56-d78d8a11e36e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNzE3OTYsIm5iZiI6MTcxMTA3MTQ5NiwicGF0aCI6Ii84OTg4NjUwNi8zMTQzNDgyNDQtNGRlODhjNmYtMDkxZS00NDc5LWJiNTYtZDc4ZDhhMTFlMzZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDAxMzgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3YTQ3OTNmNzFkMTk2NDhhODhiY2ZkODEzMGUxMzUxNjBkOWI5YzRhZWU0M2Y1Y2JlZTIzMjUzNTZmYmQ1YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.811vuYnylgNAIt4mdrQkqeH9cUSSks6Efd9J8_LWIOY)
> 
> * depth 값을 추가하면 해당 depth에 해당하는 카테고리만 보여줌
> 
> ```
> SELECT c.*
> FROM Categories as c
>          JOIN CategoryPath AS p
>               ON c.categoryId = p.descendantId
> WHERE p.ancestorId = 최상위 카테고리 id
>   AND p.depth = 세부 카테고리 id;
> ```
> 
> ![Image](https://private-user-images.githubusercontent.com/89886506/314349854-c9de12c2-5c48-450b-b339-17c7c8f54a77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNzE3OTYsIm5iZiI6MTcxMTA3MTQ5NiwicGF0aCI6Ii84OTg4NjUwNi8zMTQzNDk4NTQtYzlkZTEyYzItNWM0OC00NTBiLWIzMzktMTdjN2M4ZjU0YTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDAxMzgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ZWYwMzcwZjM0Y2I4NzZkODkzNWMyMzVlNmNmNjAzZTIyNTkwYmZhZmY5NTczNTRiNWIzYWJhMTg1MWQxNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Li5FDSvqUJVTBJoySd_zHtWFE1hoEn1S-EM1YzXL6nw)
